### ISSUE TITLE
Problem with structlog: findCaller() takes from 1 to 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by DJ2LS** [DJ2LS/FreeDATA#120]
Traceback (most recent call last):
File "daemon.py", line 28, in <module>
structlog.get_logger("structlog").info("[DMN] Starting FreeDATA daemon", author="DJ2LS", year="2022", version="0.1")
File "/usr/lib/python3/dist-packages/structlog/stdlib.py", line 67, in info
return self._proxy_to_logger("info", event, *args, **kw)
File "/usr/lib/python3/dist-packages/structlog/stdlib.py", line 117, in _proxy_to_logger
return super(BoundLogger, self)._proxy_to_logger(method_name,
File "/usr/lib/python3/dist-packages/structlog/_base.py", line 177, in _proxy_to_logger
return getattr(self._logger, method_name)(*args, **kw)
File "/usr/lib/python3.8/logging/__init__.py", line 1446, in info
self._log(INFO, msg, args, **kwargs)
File "/usr/lib/python3.8/logging/__init__.py", line 1577, in _log
fn, lno, func, sinfo = self.findCaller(stack_info, stacklevel)
TypeError: findCaller() takes from 1 to 2 positional arguments but 3 were given

**Comment by DJ2LS** [comment]
Problem could be an outdated package.

https://www.activestate.com/resources/quick-reads/how-to-update-all-python-packages/

https://stackoverflow.com/a/66453995

**Comment by DJ2LS** [comment]
Ubuntu 20.4

**Comment by DJ2LS** [comment]
This problem didn't occur the last weeks, is I'm closing it for now.
