### ISSUE TITLE
Shutdown messages

### ISSUE THREAD

**Issue by DJ2LS** [DJ2LS/FreeDATA#133]
When closing the daemon/tnc, check for returned multithreading messages and writing a nice message to the screen like "shutdown"

 ```
 File "./daemon.py", line 267, in <module>
    time.sleep(1)
KeyboardInterrupt
^CException ignored in: <module 'threading' from '/usr/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 1281, in _shutdown
    t.join()
  File "/usr/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt

```

**Comment by DJ2LS** [comment]
solved with latest commit
