### ISSUE TITLE
Alsa Error needs to be checked

### ISSUE THREAD

**Issue by DJ2LS** [DJ2LS/FreeDATA#22]
Expression 'alsa_snd_pcm_start( stream->playback.pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 4501
Expression 'alsa_snd_pcm_mmap_begin( self->pcm, &areas, &self->offset, numFrames )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 3986
Expression 'PaAlsaStreamComponent_RegisterChannels( &self->playback, &self->bufferProcessor, &playbackFrames, &xrun )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 4106
Expression 'PaAlsaStream_SetUpBuffers( stream, &framesGot, &xrun )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 4483
Exception in thread TRANSMIT_ARQ_BURST:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Speicherzugriffsfehler (Speicherabzug geschrieben)

**Comment by DJ2LS** [comment]
python3: src/hostapi/alsa/pa_linux_alsa.c:4162: PaAlsaStream_SetUpBuffers: Assertion `self->neverDropInput' failed.

**Comment by DJ2LS** [comment]
When removing audio device while usage:

```
Expression 'alsa_snd_pcm_start( stream->capture.pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2929
Expression 'AlsaStart( stream, 0 )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 3241
Expression 'AlsaRestart( self )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 3308
Expression 'PaAlsaStream_HandleXrun( self )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 3942
Expression 'PaAlsaStream_WaitForFrames( stream, &framesAvail, &xrun )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 4426
Exception in thread FREEDV_DECODER_THREAD:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/parallels/FreeDV-JATE/modem.py", line 361, in receive
    data_in = self.stream_rx.read(nin,  exception_on_overflow = False)  
  File "/usr/local/lib/python3.8/dist-packages/pyaudio.py", line 608, in read
    return pa.read_stream(self._stream, num_frames, exception_on_overflow)
OSError: [Errno -9999] Unanticipated host error
```

**Comment by DJ2LS** [comment]
We move to miniaudio library
