### ISSUE TITLE
IndexError after failed transmission

### ISSUE THREAD

**Issue by DJ2LS** [DJ2LS/FreeDATA#35]
9:52:56.417 INFO:	DATA [DJ2LS]>> <<[DN2LS] A:[1/3]
19:52:58.374 INFO:	DATA [DJ2LS]>>|<<[DN2LS] [SNR:6.7]
19:52:58.375 INFO:	ARQ | TX | M:14 | DATA FRAME --- BYTES: 106 ARQ FRAMES: 18
19:52:58.375 DATA:	ARQ | TX | M:14 | F:[1-2] | T:[0/18] [000%] | A:[1/3]
19:53:06.594 WARNING:	ARQ | RX | ACK TIMEOUT!
19:53:06.594 DATA:	ARQ | TX | M:14 | F:[1-2] | T:[0/18] [000%] | A:[2/3]
19:53:14.792 WARNING:	ARQ | RX | ACK TIMEOUT!
19:53:14.793 DATA:	ARQ | TX | M:14 | F:[1-2] | T:[0/18] [000%] | A:[3/3]
19:53:22.991 WARNING:	ARQ | RX | ACK TIMEOUT!
19:53:22.991 FAILED:	ARQ | TX | NO ACK RECEIVED | DATA SHOULD BE RESEND!
19:53:22.991 INFO:	RATE (DATA/ACK) :[34 bit/s | 259 B/min]
19:53:22.991 INFO:	ARQ | TX | BUFFER EMPTY
19:53:24.993 INFO:	DATA [DJ2LS]<< >>[DN2LS] [SNR:6.7]
19:53:32.410 INFO:	DATA [DJ2LS]>> <<[DN2LS] A:[1/3]
19:53:34.855 INFO:	DATA [DJ2LS]>>|<<[DN2LS] [SNR:-1.6]
19:53:34.860 INFO:	ARQ | TX | M:12 | DATA FRAME --- BYTES: 106 ARQ FRAMES: 1
19:53:34.860 DATA:	ARQ | TX | M:12 | F:[1-1] | T:[0/1] [000%] | A:[1/3]
19:53:39.664 WARNING:	ARQ | RX | REQUEST FOR REPEATING FRAMES: [b'\x00\x02']
19:53:39.664 WARNING:	ARQ | TX | SENDING REQUESTED FRAMES: [b'\x00\x02']
Exception in thread ARQ_DATA:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/parallels/FreeDV-JATE/data_handler.py", line 524, in open_dc_and_transmit
    arq_transmit(data_out)
  File "/home/parallels/FreeDV-JATE/data_handler.py", line 341, in arq_transmit
    modem.transmit_arq_burst()
  File "/home/parallels/FreeDV-JATE/modem.py", line 327, in transmit_arq_burst
    payload_data = bytes(static.TX_BUFFER[static.ARQ_N_SENT_FRAMES + missing_frame - 1])
IndexError: list index out of range

**Comment by DJ2LS** [comment]
not relevant anymore. IndexError doesn't occure with latest version
