### ISSUE TITLE
TCI fails on latest  development branch

### ISSUE THREAD

**Issue by LA3QMA** [DJ2LS/FreeDATA#581]
2023-12-21 16:26:10 [warning  ] [MDM] [TCI] Not yet fully implemented ip=127.0.0.1 port=50001
2023-12-21 16:26:10 [info     ] [TCI] Starting TCI thread!     ip=127.0.0.1 port=50001
Exception in thread runner thread:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kgb/FreeDATA/modem/service_manager.py", line 38, in runner
    self.start_modem()
  File "/home/kgb/FreeDATA/modem/service_manager.py", line 82, in start_modem
    self.modem.start_modem()
  File "/home/kgb/FreeDATA/modem/modem.py", line 123, in start_modem
    result = self.init_tci()
             ^^^^^^^^^^^^^^^
  File "/home/kgb/FreeDATA/modem/modem.py", line 218, in init_tci
    target=self.tci_rx_callback,
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RF' object has no attribute 'tci_rx_callback'. Did you mean: 'tci_tx_callback'?
2023-12-21 16:26:10 [info     ] [TCI] Connected FreeDATA to TCI rig! ip=127.0.0.1 port=50001
2023-12-21 16:26:10 [info     ] [TCI] Init...                  ip=127.0.0.1 port=50001

**Comment by DJ2LS** [comment]
please move latest state to Trello
