### ISSUE TITLE
redesign transfer rate calculation

### ISSUE THREAD

**Issue by DJ2LS** [DJ2LS/FreeDATA#66]
Exception in thread ARQ_DATA:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dn2ls/codec2-FreeDATA/tnc/data_handler.py", line 544, in open_dc_and_transmit
    arq_transmit(data_out)
  File "/home/dn2ls/codec2-FreeDATA/tnc/data_handler.py", line 314, in arq_transmit
    helpers.calculate_transfer_rate() 
  File "/home/dn2ls/codec2-FreeDATA/tnc/helpers.py", line 158, in calculate_transfer_rate
    static.ARQ_BITS_PER_SECOND = int((static.TOTAL_BYTES * 8) / total_transmission_time)
TypeError: unsupported operand type(s) for /: 'bytes' and 'float'

**Comment by DJ2LS** [comment]
We need to redesign the transfer rate calculation

**Comment by DJ2LS** [comment]
Already done with latest modem version.
We could do some more cleanup
