### ISSUE TITLE
TypeError: The view function for 'post_beacon' did not return a valid response.

### ISSUE THREAD

**Issue by OH2JRB** [DJ2LS/FreeDATA#717]
**Describe the bug**
TypeError: The view function for 'post_beacon' did not return a valid response.
The function either returned None or ended without a return statement.

**To Reproduce**
In main FreeDATA GUI window, change Enable Beacon or Away from Key status.

**Expected behavior**
Simple action without errors in console log.

**Screenshots**
127.0.0.1 - - [04/May/2024 16:19:16] "POST /modem/beacon HTTP/1.1" 500 -
[2024-05-04 16:19:18,032] ERROR in app: Exception on /modem/beacon [POST]
Traceback (most recent call last):
  File "/root/venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.11/site-packages/flask/app.py", line 889, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.11/site-packages/flask/app.py", line 1161, in make_response
    raise TypeError(
TypeError: The view function for 'post_beacon' did not return a valid response. The function either returned None or ended without a return statement.
127.0.0.1 - - [04/May/2024 16:19:18] "POST /modem/beacon HTTP/1.1" 500 -
2024-05-04 16:20:55 [info     ] Running BeaconCommand         
2024-05-04 16:20:55 [debug    ] [MDM] TRANSMIT                 delay=50 mode=signalling
2024-05-04 16:20:55 [debug    ] Event:                         ev={'ptt': True}
2024-05-04 16:20:57 [debug    ] Event:                         ev={'ptt': False}
2024-05-04 16:20:57 [debug    ] [MDM] ON AIR TIME              time=2.3316895961761475

**Desktop (please complete the following information):**
Intel NUC running Debian Bookworm

**Additional context**
GUI 0.15.6-alpha.
Modem 0.15.6-alpha.

**Comment by DJ2LS** [comment]
probably fixed, please do a git pull
