### ISSUE TITLE
Hamlib Windows support

### ISSUE THREAD

**Issue by DJ2LS** [DJ2LS/FreeDATA#76]
We should wait until Hamlib released windows support.
https://github.com/Hamlib/Hamlib/issues/201

**Comment by DJ2LS** [comment]
...gui and tnc seem to work. Current problem is the hamlib binding for python, which has no windows support yet

**Comment by DJ2LS** [comment]
with rigctl support this should be able to run. Further tests are needed. 
Also added some path changes. The GUI is working, but we need to find a way creating an app bundle for easier testing.

**Comment by DJ2LS** [comment]
- we need to update codec2 search path looking for dll 
- codec2.py line47 quit() not defied
- rigctl path not found in lib/hamlib/...

**Comment by DJ2LS** [comment]
```
Traceback (most recent call last):
  File "main.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "data_handler.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "modem.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "codec2.py", line 76, in <module>
  File "ctypes\__init__.py", line 444, in __getattr__
TypeError: 'str' object is not callable
[1828] Failed to execute script 'main' due to unhandled exception!
```

**Comment by DJ2LS** [comment]
latest commit seem to work for windows. 
We still have problems with  closing the child processes for the tnc binary triggered by the daemin when closing the gui.
