### ISSUE TITLE
[Bug]: Modem makes error if grid square is less than 6character

### ISSUE THREAD

**Issue by LA3QMA** [DJ2LS/FreeDATA#815]
### FreeDATA Version

0.16.4-alpha

### What operating system are you using?

Other (specify below)

### Operating System Version

Both linux/windows

### Architecture

x64

### Area of problem

Server - General

### Describe the bug

If the grid square is empty or less than 6 characters modem responds with:
Gridsquare must be 6 characters!
2024-09-23 16:35:11 [info     ] [API] POST                     response_code=200 url=http://127.0.0.1:5000/config
2024-09-23 16:35:19 [info     ] [API] POST                     response_code=200 url=http://127.0.0.1:5000/modem/beacon
Command BeaconCommand running...
2024-09-23 16:35:20 [info     ] Running BeaconCommand
Command failed: string index out of range

### To Reproduce

Change grid square to be less than 6 characters

### Expected behavior

If the user has forgot to set the grid square or if its less than 6 characters warn with a popup in the GUI.
The modem reports if the grid square is wrong but should handle this so that there are no errors.

Either add random characters if its less than 6 characters.

**Comment by LA3QMA** [comment]
This errors appears after a wrong grid has been used so i guess this is a consequence of the wrong grid.

 15:38:57 [info     ] [ARQSessionIRS][id=51][state=IRS_State.ENDED]: ARQSessionIRS state change from ENDED to RESUME at 1727098737.0425534
2024-09-23 15:38:57 [info     ] [ARQSessionIRS][id=62][state=IRS_State.FAILED]: ARQSessionIRS state change from FAILED to RESUME at 1727098737.0426075
2024-09-23 15:38:57 [info     ] [ARQSessionIRS][id=110][state=IRS_State.FAILED]: ARQSessionIRS state change from FAILED to RESUME at 1727098737.042661
2024-09-23 15:39:54 [info     ] [EXPLORER] Data pushed successfully
Exception in thread Thread-77 (run):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/sched.py", line 151, in run
    action(*argument, **kwargs)
  File "/home/kgb/freedata/FreeDATA/freedata_server/schedule_manager.py", line 42, in schedule_event
    event_function()  # Execute the event function
  File "/home/kgb/freedata/FreeDATA/freedata_server/schedule_manager.py", line 119, in update_transmission_state
    session.state = session.set_state(IRS_State.RESUME)
  File "/home/kgb/freedata/FreeDATA/freedata_server/arq_session.py", line 116, in set_state
    self.log(f"{type(self).__name__} state change from {self.state.name} to {state.name} at {self.last_state_change_timestamp}")
AttributeError: 'NoneType' object has no attribute 'name'
